export default {
    path:"/usercenter",
    component:()=>import("../../view/usercenter/index.vue"),
    meta:{
      requireAuth:true
    },
    children:[
        {
            path:"userInfo",
            component:()=>import("../../components/userInfo"),
            meta:{
                requireAuth:true
            },

        },
        {
            path:"mycourse",
            component:()=>import("../../components/mycourse"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"myexam",
            component:()=>import("../../components/myexam"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"mynews",
            component:()=>import("../../components/mynews"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"coursemanage",
            component:()=>import("../../view/coursemanage"),
            meta:{
                requireAuth:true
            },
            children: [
                {
                    path:"addcourse",
                    component:()=>import("../../view/coursemanage/addcourse"),
                    meta:{
                        requireAuth:true
                    },
                    children:[
                        {
                            path:"addarticle",
                            component:()=>import("../../view/coursemanage/addcourse/article")
                        },
                        {
                            path:"addvideo",
                            component:()=>import("../../view/coursemanage/addcourse/video")
                        }
                    ]
                },
                {
                    path:"changecourse",
                    component:()=>import("../../view/coursemanage/changecourse"),
                    meta:{
                        requireAuth:true
                    },
                },
                {
                    path:"showcourse",
                    component:()=>import("../../view/coursemanage/showcourse"),
                    meta:{
                        requireAuth:true
                    },
                },
            ]
        },
        {
            path:"exammanage",
            component:()=>import("../../view/exammanage"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"newsmanage",
            component:()=>import("../../view/newsmanage"),
            meta:{
                requireAuth:true
            },
            children: [
                {
                    path:"addnews",
                    component:()=>import("../../view/newsmanage/addnews"),
                    meta:{
                        requireAuth:true
                    },
                },
                {
                    path:"changenews",
                    component:()=>import("../../view/newsmanage/changenews"),
                    meta:{
                        requireAuth:true
                    },
                },
                {
                    path:"shownews",
                    component:()=>import("../../view/newsmanage/shownews"),
                    meta:{
                        requireAuth:true
                    },
                },
            ]
        },
    ]
}
