export default {
    path:"/usercenter",
    component:()=>import("../../view/usercenter/index.vue"),
    meta:{
      requireAuth:true
    },
    children:[
        {
            path:"userInfo",
            component:()=>import("../../components/userInfo"),
            meta:{
                requireAuth:true
            },

        },
        {
            path:"usermanage",
            component:()=>import("../../view/usermanage"),
            meta:{
                requireAuth:true
            },

        },
        {
            path:"mycourse",
            component:()=>import("../../view/mycourse"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"myexam",
            component:()=>import("../../view/myexam"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"mynews",
            component:()=>import("../../view/mynews"),
            meta:{
                requireAuth:true
            },
        },
        {
            path:"coursemanage",
            component:()=>import("../../view/coursemanage"),
            meta:{
                requireAuth:true
            },
            children: [
                {
                    path:"addcourse",
                    component:()=>import("../../view/coursemanage/addcourse"),
                    meta:{
                        requireAuth:true
                    },
                    children:[
                        {
                            path:"addarticle",
                            component:()=>import("../../view/coursemanage/addcourse/article")
                        },
                        {
                            path:"addvideo",
                            component:()=>import("../../view/coursemanage/addcourse/video")
                        }
                    ]
                },
                {
                    path:"changecourse",
                    component:()=>import("../../view/coursemanage/changecourse"),
                    meta:{
                        requireAuth:true
                    },
                    children:[
                        {
                            path:"article",
                            component:()=>import("../../view/coursemanage/changecourse/article.vue")
                        },
                        {
                            path:"video",
                            component:()=>import("../../view/coursemanage/changecourse/video.vue")
                        }
                    ]
                },
                {
                    path:"showcourse",
                    component:()=>import("../../view/coursemanage/showcourse"),
                    meta:{
                        requireAuth:true
                    },
                },
            ]
        },
        {
            path:"exammanage",
            component:()=>import("../../view/exammanage"),
            meta:{
                requireAuth:true
            },
            children:[
                {
                    path:"addexam",
                    component:()=>import("../../view/exammanage/addexam")
                },
                {
                    path:"showexam",
                    component:()=>import("../../view/exammanage/showexam")
                },
                {
                    path:"changeexam",
                    component:()=>import("../../view/exammanage/changeexam")
                },
                {
                    path:"showgrade/:eid",
                    component:()=>import("../../view/exammanage/showexam/showgrade"),
                    props:true
                }
            ]
        },
        {
            path:"newsmanage",
            component:()=>import("../../view/newsmanage"),
            meta:{
                requireAuth:true
            },
            children: [
                {
                    path:"addnews",
                    component:()=>import("../../view/newsmanage/addnews"),
                    meta:{
                        requireAuth:true
                    },
                },
                {
                    path:"changenews",
                    component:()=>import("../../view/newsmanage/changenews"),
                    meta:{
                        requireAuth:true
                    },
                },
                {
                    path:"shownews",
                    component:()=>import("../../view/newsmanage/shownews"),
                    meta:{
                        requireAuth:true
                    },
                },
            ]
        },
        {
            path:"message/:cid",
            component:()=>import("../../view/message"),
            props:true,
            meta:{
                requireAuth:true
            },
        },
        {
            path:"reply/:mid",
            component:()=>import("../../view/reply"),
            props:true,
            meta:{
                requireAuth:true
            },
        }
    ]
}
